# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing
change_language:
  url:  /change_language
  param:  {module: language, action: changeLanguage}

localized_homepage:
  url: /:sf_culture/
  param: {module: job, action: index}
  requirements:
    sf_culture: (?:fr|en)

job_search:
  url:  /:sf_culture/search
  param: {module:job, action:search}

affiliate:
  class: sfPropelRouteCollection
  options:
    model:  JobeetAffiliate
    actions: [new, create]
    object_actions: {wait: get}
    prefix_path:   /:sf_culture/affiliate

api_jobs:
  url:   /api/:token/jobs.:sf_format
  class: sfPropelRoute
  param: { module: api, action: list }
  options: { model: JobeetJob, type: list, method: getForToken }
  requirements:
    sf_format: (?:xml|json|yaml)

category:
  url:    /:sf_culture/category/:slug.:sf_format
  class:  sfPropelRoute
  param:  { module: category, action: show, sf_format: html}
  options: { model: JobeetCategory, type: object }
  requirements:
    sf_format: (?:html|atom)

job:
  class:  sfPropelRouteCollection
  options:
    model:  JobeetJob
    column: token
    object_actions:
      publish: put
      extend: put
  requirements:
    token: \w+

job_show_user:
  url:  /:sf_culture/job/:company_slug/:location_slug/:id/:position_slug
  class: sfPropelRoute
  options:  { model: JobeetJob, type: object, method_for_criteria: doSelectActive }
  param:  { module: job, action: show }
  requirements:
    id: \d+
    sf_method: [GET]

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*


