<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/04/16 10:34:06
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 20,
));
