<?php


/**
 * Skeleton subclass for representing a row from the 'jobeet_affiliate' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * 12/17/12 18:28:04
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class JobeetAffiliate extends BaseJobeetAffiliate {


	/**
	 * author: zhangyiqun
	*/
	public function __toString()
	{
		return $this->getUrl();
	}
	
	/**
	 * Initializes internal state of JobeetAffiliate object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

    public function save(PropelPDO $con = null)
    {
        if(!$this->getToken())
        {
            $this->setToken(sha1($this->getEmail().rand(11111,99999)));
        }

        return parent::save($con);
    }

    public function getActiveJobs()
    {
        $cas = $this->getJobeetCategoryAffiliates();
        $categories = array();
        foreach($cas as $ca)
        {
            $categories[] = $ca->getCategoryId();
        }

        $criteria = new Criteria();
        $criteria ->add(JobeetJobPeer::CATEGORY_ID, $categories, Criteria::IN);
        JobeetJobPeer::addActiveJobsCriteria($criteria);

        return JobeetJobPeer::doSelect($criteria);
    }

    public function activate()
    {
        $this->setIsActive(true);

        return $this->save();
    }

    public function deactivate()
    {
        $this->setIsActive(false);

        return $this->save();
    }

} // JobeetAffiliate
