<?php


/**
 * Skeleton subclass for representing a row from the 'jobeet_job' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * 12/17/12 18:28:04
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class JobeetJob extends BaseJobeetJob {

    public function getTypeName()
    {
        return $this->getType() ? JobeetJobPeer::$types[$this->getType()] : '';
    }

    public function isExpired()
    {
        return $this->getDaysBeforeExpires() < 0;
    }

    public function expiresSoon()
    {
        return $this->getDaysBeforeExpires() < 5;
    }

    public function getDaysBeforeExpires()
    {
        return ceil(($this->getExpiresAt('U') - time())/86400);
    }

    public function publish()
    {
        $this->setIsActivated(true);
        $this->save();
    }

    public function extend($force = false)
    {
        if(!$force && !$this->expiresSoon())
        {
            return false;
        }

        $this->setExpiresAt(time() + 86400 * sfConfig::get('app_active_days'));
        $this->save();

        return true;
    }

    public function asArray($host)
    {
        return array(
            'category'  => $this->getJobeetCategory()->getName(),
            'type'      => $this->getType(),
            'company'   => $this->getCompany(),
            'logo'      => $this->getLogo() ? 'http://'.$host.'/uploads/jobs/'.$this->getLogo():null,
            'url'       => $this->getUrl(),
            'position'  => $this->getPosition(),
            'location'  => $this->getLocation(),
            'description'=> $this->getDescription(),
            'how_to_apply'=> $this->getHowToApply(),
            'expires_at'  => $this->getCreatedAt('c'),
        );
    }

	/**
	 * author:zhangyiqun
	*/
	public function __toString()
	{
		return sprintf('%s at %s (%s)',$this->getPosition(),$this->getCompany(),$this->getLocation());
	}
	
	/**
	 * Initializes internal state of JobeetJob object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}
	
	/**
	 * Get the [company] column value and slug the value.
	 * 
	 * @return     string
	 */
	public function getCompanySlug()
	{
		return Jobeet::slugify($this->getCompany());
	}
	
	
	/**
	 * Get the [location] column value and slug the value.
	 * 
	 * @return     string
	 */
	public function getLocationSlug()
	{
		return Jobeet::slugify($this->getLocation());
	}
	
		/**
	 * Get the [position] column value and slug the value.
	 * 
	 * @return     string
	 */
	public function getPositionSlug()
	{
		return Jobeet::slugify($this->getPosition());
	}
	
	public function save(PropelPDO $con = null)
	{
        if(!$this->getToken())
        {
            $this->setToken(sha1($this->getEmail().rand(11111,99999)));
        }
		if($this->isNew() && !$this->getExpiresAt())
		{
			$now = $this->getCreatedAt() ? $this->getCreatedAt('U'):time();
			$this->setExpiresAt($now + 86400 * sfConfig::get('app_active_days'));
		}
		
		return parent::save($con);
	}
} // JobeetJob
